export default {
  GETRENCENTCHAT: "GETRENCENTCHAT",
  GETRENCENTCHATBYID: "GETRENCENTCHATBYID",
  GETMESSAGE: "GETMESSAGE",
  GETMESSAGEBYID: "GETMESSAGEBYID",
  POSTMESSAGE: "POSTMESSAGE",
  DELETEMESSAGE: "DELETEMESSAGE",
  ONLINEUSER: "ONLINEUSER",
  OFFLINEUSER: "OFFLINEUSER",
  TEST: "64ae96f1daaeb5789f9389fd",
};
